package com.skip.FatApp.data

import android.content.Context
import java.time.LocalDate
import java.time.ZoneId
import java.time.format.DateTimeFormatter

private const val PREFS_NAME = "fatapp_steps_auto"
private const val KEY_YESTERDAY_MAX = "yesterday_max_steps"
private const val KEY_LAST_DATE = "last_steps_date"

private const val KEY_YESTERDAY_DATE = "yesterday_date"

object AutoWalkingLogger {

    private val dateFormatter = DateTimeFormatter.ISO_LOCAL_DATE

    /**
     * Call this on app start / foreground.
     * If a new day is detected, create a Walking entry for yesterday
     * if one does not already exist, and return its steps (or null).
     */
    suspend fun maybeCreateYesterdayWalkingEntry(
        context: Context,
        activityDao: ActivityDao,
        currentCounter: Long
    ): Int? {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

        val today = LocalDate.now().format(dateFormatter)
        val lastDate = prefs.getString(KEY_LAST_DATE, null)

        // First run ever – just store today and exit
        if (lastDate == null) {
            prefs.edit()
                .putString(KEY_LAST_DATE, today)
                .putLong(KEY_YESTERDAY_MAX, currentCounter)
                .apply()
            return null
        }

        // Same day – nothing to do
        if (lastDate == today) {
            return null
        }

        // New day – try to create entry for yesterday
        val yesterday = LocalDate.parse(lastDate, dateFormatter)
        val yesterdayStartMillis = yesterday
            .atStartOfDay(ZoneId.systemDefault())
            .toInstant()
            .toEpochMilli()

        val yesterdayEndMillis = yesterdayStartMillis + 86_400_000L

        // Check if a Walking entry already exists for yesterday
        val existing = activityDao.getWalkingEntriesForDay(
            dayStartMillis = yesterdayStartMillis,
            dayEndMillis = yesterdayEndMillis
        ).firstOrNull()

        val yesterdayMax = prefs.getLong(KEY_YESTERDAY_MAX, 0L).toInt()

        if (existing == null && yesterdayMax > 0) {
            // Create automatic Walking entry
            val entry = ActivityEntry(
                id = 0, // will be generated by DB
                type = ActivityType.WALKING,
                activityName = null,
                dateMillis = yesterdayStartMillis,
                steps = yesterdayMax,
                durationMinutes = null,
                estimatedCalories = 0 // can be refined later if needed
            )
            activityDao.insert(entry)
        }

        // Update stored date and reset max for today
        prefs.edit()
            .putString(KEY_LAST_DATE, today)
            .putLong(KEY_YESTERDAY_MAX, currentCounter)
            .apply()

        return if (existing == null && yesterdayMax > 0) yesterdayMax else null
    }

    /**
     * Call this whenever today's steps increase, to update yesterdayMax
     * (which will become today's max when day rolls over).
     */
    fun updateYesterdayMax(context: Context, todaySteps: Int) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val currentMax = prefs.getLong(KEY_YESTERDAY_MAX, 0L).toInt()
        if (todaySteps > currentMax) {
            prefs.edit()
                .putLong(KEY_YESTERDAY_MAX, todaySteps.toLong())
                .apply()
        }
    }
    /**
     * Reset the stored baseline when the user enables step tracking.
     * This prevents old step counts from being used as "yesterday's max".
     */
    fun resetBaseline(context: Context) {
        val prefs = context.getSharedPreferences(
            "auto_walking_prefs",
            Context.MODE_PRIVATE
        )
        prefs.edit()
            .remove(KEY_YESTERDAY_MAX)
            .remove(KEY_YESTERDAY_DATE)
            .apply()
    }
}